@startuml

/'






'/

interface SqlStatement {
}

interface QueryExecutor {
+ QueryResult execute(Query query)
}

interface Query {
+ Map<dynamic, QueryParameter> parameters;
+ SqlStatement statement
+ ResultSetDescriptor resultSetDescriptor;
}

interface QueryParameter {
+ QueryValueDescriptor descriptor
+ value
}

interface QueryValueDescriptor {
}

interface QueryResult {
}

/'

'/
interface QueryResultSet {
+ int lastInsertId
+ int affectedRowsCount
+ List<QueryResultSetRow> rows
}

/'

'/
interface QueryResultSetRow {
}

@enduml